// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFile(arg1) {
  return window['go']['main']['App']['AddFile'](arg1);
}

export function BindPeerWithPhrase(arg1) {
  return window['go']['main']['App']['BindPeerWithPhrase'](arg1);
}

export function CancelBinding() {
  return window['go']['main']['App']['CancelBinding']();
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateNewVault() {
  return window['go']['main']['App']['CreateNewVault']();
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function ExportFile(arg1, arg2) {
  return window['go']['main']['App']['ExportFile'](arg1, arg2);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetFolderPath(arg1) {
  return window['go']['main']['App']['GetFolderPath'](arg1);
}

export function GetNodeID() {
  return window['go']['main']['App']['GetNodeID']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetStorageStats() {
  return window['go']['main']['App']['GetStorageStats']();
}

export function GetSyncPhrase() {
  return window['go']['main']['App']['GetSyncPhrase']();
}

export function IsMaster() {
  return window['go']['main']['App']['IsMaster']();
}

export function ListFolder(arg1) {
  return window['go']['main']['App']['ListFolder'](arg1);
}

export function RemovePeer(arg1) {
  return window['go']['main']['App']['RemovePeer'](arg1);
}

export function StartReplicaBinding() {
  return window['go']['main']['App']['StartReplicaBinding']();
}

export function UnlockWithMnemonic(arg1) {
  return window['go']['main']['App']['UnlockWithMnemonic'](arg1);
}
