// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFile(arg1:number):Promise<void>;

export function BindPeerWithPhrase(arg1:string):Promise<void>;

export function CancelBinding():Promise<void>;

export function CreateFolder(arg1:string,arg2:number):Promise<number>;

export function CreateNewVault():Promise<string>;

export function DeleteFile(arg1:string,arg2:number):Promise<void>;

export function DeleteFolder(arg1:number):Promise<void>;

export function ExportFile(arg1:string,arg2:number):Promise<void>;

export function GetAppState():Promise<string>;

export function GetFolderPath(arg1:number):Promise<Array<main.PathSegment>>;

export function GetPeers():Promise<Array<main.PeerInfo>>;

export function GetSyncPhrase():Promise<string>;

export function IsMaster():Promise<boolean>;

export function ListFolder(arg1:number):Promise<Array<main.FolderItem>>;

export function RemovePeer(arg1:string):Promise<void>;

export function StartReplicaBinding():Promise<string>;

export function UnlockWithMnemonic(arg1:string):Promise<void>;
